name: Jake Mills
favicon: null
layout_spectrum: 1
typography_spectrum: 0.908113362500444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272727'
    - '#e7e7e7'
    - '#c0c0c0'
    - '#9c9c9c'
    - '#7f7f7f'
  brandStrength: 0.4375
  lightness: 0.6375924425665289
  saturation: 0.8415065223816782
  rhythmicContrast: 0.2707475363276899
purpose: []
