name: Jake Mills
favicon: null
layout_spectrum: 0.6816897820681334
typography_spectrum: 0.908113362500444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4391861967742443
  lightness: 0.6375924425665289
  saturation: 0.8415065223816782
  rhythmicContrast: 0.2707475363276899
purpose: []
